### ISSUE TITLE
Неправильное отображение карточки сотрудника при нажатии

### ISSUE THREAD

**Issue by sushkomihail** [MishailAJ/new_aitip_site#22]
![image](https://github.com/MishailAJ/new_aitip_site/assets/68999090/04848679-0e2c-4424-baeb-05c9110583a9)

ветка main

**Comment by RAZRULETEL** [comment]
> ![image](https://user-images.githubusercontent.com/68999090/252553535-04848679-0e2c-4424-baeb-05c9110583a9.png)
> 
> ветка main

![image](https://github.com/MishailAJ/new_aitip_site/assets/48093833/f3bb41b5-68ec-46e2-a82b-13e3c202bb9e)
