### ISSUE TITLE
Страница admission_bac

### ISSUE THREAD

**Issue by Intention-man** [MishailAJ/new_aitip_site#27]
1) Картинка вылезает за рамки: <img width="752" alt="image" src="https://github.com/MishailAJ/new_aitip_site/assets/74947150/27c30ceb-72cf-4090-9688-080ed4551531">
2) Стили полетели: <img width="589" alt="image" src="https://github.com/MishailAJ/new_aitip_site/assets/74947150/a48dc239-64cb-4ab0-a1e9-2e35fc83d560">
3) У текста нет отступов от краев (Ване нужно определиться со значениями)
<img width="647" alt="image" src="https://github.com/MishailAJ/new_aitip_site/assets/74947150/1bd9dad8-e1cd-45c7-9f5c-d8f60591e4db">

**Comment by RAZRULETEL** [comment]
Fixed, last commit
