### ISSUE TITLE
Исчезающая картинка снизу растягивается не на всю ширину

### ISSUE THREAD

**Issue by Intention-man** [MishailAJ/new_aitip_site#35]
Заметил эту проблему только сегодня (13.08)

<img width="740" alt="image" src="https://github.com/MishailAJ/new_aitip_site/assets/74947150/09f17518-a400-4015-b207-b1fd1901b736">
<img width="730" alt="image" src="https://github.com/MishailAJ/new_aitip_site/assets/74947150/f9e92ecf-7057-4494-8f9f-335964c4148e">

**Comment by IB004** [comment]
Еще прошу сделать градиент менее длинным. На фото часто люди, а лица получаются покрыты белым переходом. На фото выше это хорошо видно
