### ISSUE TITLE
Пропал переход на новую строку

### ISSUE THREAD

**Issue by IB004** [MishailAJ/new_aitip_site#36]
Ранее в конструкторе можно было перейти на новую строку без пропуска строки. Теперь нет
![изображение](https://github.com/MishailAJ/new_aitip_site/assets/123304942/4620d8fe-30a8-475f-9355-a4a50295ca75)

**Comment by amphyxs** [comment]
В Markdown так и должно быть. Перенос на новую строку делается, когда между строками есть пустая.
Так сделано, чтобы можно было переносить длинный текст.
