### ISSUE TITLE
Картинки сбоку должны полностью помещаться

### ISSUE THREAD

**Issue by IB004** [MishailAJ/new_aitip_site#44]
![image](https://github.com/MishailAJ/new_aitip_site/assets/123304942/c38cc52e-828d-4bda-86af-ccdcf19964ff)

Пример на Юр клинике: http://new-aitip.aitipms7.beget.tech/legal_clinic

**Comment by RAZRULETEL** [comment]
![image](https://github.com/MishailAJ/new_aitip_site/assets/48093833/024ec90f-da9b-4cde-a8a2-8e9450bbe7c6)
Если сломаются карточки в других местах, переоткройте.
