### ISSUE TITLE
Документы: отступы и значок

### ISSUE THREAD

**Issue by IB004** [MishailAJ/new_aitip_site#48]
**Значок:**
1) значок нужно заменить на более новый цвет и в формате svg (положил в материалы беседы Телеграмм)
2) значок должен не менять свои пропорции при масштабировании (сейчас он и так не меняет, но вдруг начнет - не должен)

**Отступы:**
Документы должны подчиняться общим правилам отступов:
40 между линиями
60 до конца документа
100 по бокам

У нас:
![image](https://github.com/MishailAJ/new_aitip_site/assets/123304942/067a5f5c-a713-4fa7-9859-3236e2e4be1c)

Должно быть:
![image](https://github.com/MishailAJ/new_aitip_site/assets/123304942/622d4fd8-c00f-48d4-b031-10737e069fc1)

**Comment by Intention-man** [comment]
Сделал по-другому, выглядит красивее (субъективно)
