### ISSUE TITLE
Узнать о нас больше - корректировки 

### ISSUE THREAD

**Issue by IB004** [MishailAJ/new_aitip_site#51]
1) Отступы должны быть от заголовка до кнопок

2) Цветные плиточки - это кнопки. При нажатии они должны менять цвет на активный, а при отжатии - становиться обратно "блеклыми". 
Напомню значения "блеклых" цветов:
light-blue: #A3BCEB
light-red: #E7B09F
light-white: #FAFAFA

3) Под кнопками должен быть серый прямоугольник, цветом фона сайта (на макетах это #F5F5F5). 
Серый фон нужен для выделения белых кнопок и чтобы в целом этот блок выглядел лучше.
От кнопок до заголовка сверху и до блока с описанием снизу должно быть примерно по 20 пикселей серого фона (то есть серый фон не заканчивается ровно по границе верхней и нижней серой кнопки, а есть еще внизу)

Сейчас (желтая рамка - примерная граница серого фона):
![image](https://github.com/MishailAJ/new_aitip_site/assets/123304942/510fc68b-1ab2-4d0f-af07-a67987156102)

Должно быть (серый фон сзади):
![image](https://github.com/MishailAJ/new_aitip_site/assets/123304942/5ed803f9-eb51-42c2-baa9-f4f63c9aa8f7)

**Comment by RAZRULETEL** [comment]
![image](https://github.com/MishailAJ/new_aitip_site/assets/48093833/32ba9f29-ca77-44f0-b8e0-194a9c1e6c04)
